common: Add message queue tests
zephyrproject-rtos/rtos-benchmark pull request #12
Opened 2023-10-30 06:28 UTC by BinCaoWR

This commit adds message queue tests, and enables running on VxWorks.

2023-11-01 15:16 UTC, peter-mitsis commented on h/bench_api.h
> + * @return BENCH_SUCCESS on success or BENCH_ERROR on failure
Thanks for catching these. :)

2023-11-01 15:16 UTC, peter-mitsis commented on h/bench_api.h
> + * This routine deletes a message queue object, and clean up any resources.
Minor typo: clean -> cleans

2023-11-01 15:16 UTC, peter-mitsis commented on src/common/bench_message_queue_test.c
> +	bench_message_queue_create(0, MQ_NAME, MSG_NUM, MSG_LEN);
General comment ... I notice that the IDs for both threads and message queues created are using hard-coded magic numbers such as 0 and 1. Can you abstract that out slightly with a macro? It is not incorrect as written, but that should make it easier to follow and verify.

An example of this can be found in bench_thread_test.c where we use THREAD_LOW, THREAD_HIGH and THREAD_SPAWN.

2023-11-01 15:16 UTC, peter-mitsis commented on src/common/bench_message_queue_test.c
> +static void gather_send_receive_context_switch_stats(int priority, int iteration)
Hmm ... the context message queue send/receive with context switching is tricky. I may have misunderstood, but I don't think that the message queue receive case for context switching is quite right as it measures the time it takes to block and switch, and not receive and switch. As I think about this more, perhaps a block and switch should be its own case.

As far as receive and switch, the best that I can come up with is to create a full message queue that has a sender waiting to have a message queue with zero elements with a high priority sender waiting to send. A lower priority receiver calls bench_message_queue_receive() and gets the message directly from the waiting sender. This assumes that the underlying message queue allows both such direct copying (I know that both VxWorks and Zephyr do) and a zero element message queue (I don't think VxWorks supports a zero element message queue and I am not 100% sure off hand if Zephyr does).

The second best that I can think of is to have a full message queue with a high priority waiting sender. A lower priority receiver calls bench_message_queue_receive() and gets the message from the message queue's internal buffer. If we take the final timestamp after the sender returns, we will have measured the time it takes for the receiver to get a message, do a context switch AND have the sender copy its data into the message queue.

That being said, I think the portion where we get the time to send a message with context switch is correct.

2023-11-03 05:49 UTC, BinCaoWR commented
@peter-mitsis , Thanks for your comments, the code is now updated according to your suggestions.

2023-11-03 07:08 UTC, BinCaoWR commented on src/common/bench_message_queue_test.c
> +static void gather_send_receive_context_switch_stats(int priority, int iteration)
Thanks for the suggestion. I have updated the receive case as you suggested "the time it takes for the receiver to get a message, do a context switch AND have the sender copy its data into the message queue".

The following is just an explanation for the consideration of the original implementation.
The logic of the original implementation is quite similar as what we are doing for semaphore in bench_sem_context_switch_test.c, and one of the whole workflows of using send & receive can be covered with the combination of the original send & receive cases.
However of cause, as you commented, the original receive case itself does not cover the whole path of the receive function.

2023-11-14 04:10 UTC, peter-mitsis approved these changes

2023-11-14 04:10 UTC, merged

2023-12-03 23:16 UTC, BlingBling43 requested changes
Noted