NuttX:new support for NuttX platform
zephyrproject-rtos/rtos-benchmark pull request #6
Opened 2022-12-28 03:35 UTC by crafcat7

This change is intended to add the ability to run rtos-benchmark on the NuttX platform

2023-01-04 20:18 UTC, peter-mitsis requested changes
Adding support for comparing against another RTOS--fantastic!

I have one request before giving it the approval for rebase/merge. As this benchmark suite is a sub-project of Zephyr, I think it would worthwhile to follow its coding style (see https://docs.zephyrproject.org/latest/contribute/guidelines.html#coding-style). How does that apply here?  Please use tabs for indentation instead spaces, where 1 tab is equivalent to 8 spaces.

2023-01-05 10:02 UTC, crafcat7 commented
I am glad to receive your suggestion, on top of this I have made certain code formatting changes with the code,  thank you!

2023-01-05 14:46 UTC, peter-mitsis commented
Almost there.

My apologies for not noticing this the first time.  Commit entries should be signed off. See https://docs.zephyrproject.org/latest/contribute/guidelines.html#developer-certification-of-origin-dco .

Second, the merge commit is not required, and should be deleted. We do our best to maintain a linear git history, so we tend to use "git rebase". The basic work flow is ...

```
git checkout main
git pull
git rebase -i main <your-branch>   // -i = interactive mode (allows for squashing, editing and dropping of commits)
git push -f origin <your-branch>   // -f = force the push (will replace the old branch if it exists)
```

2023-01-06 05:06 UTC, crafcat7 commented
Thank you for your suggestions, changes have been made.

2023-01-06 18:35 UTC, peter-mitsis approved these changes

2023-01-06 18:35 UTC, merged